class BaseConfig(object):
    SERIAL_INTERFACE = 'CP2102'

    OUTLET_0_NAME = 'Outlet 0'
    OUTLET_1_NAME = 'Outlet 1'
    OUTLET_2_NAME = 'Outlet 2'

    AUTO_LIGHT_OUTLET_ID = 0
    LIGHT_OFF_HOUR = 23
    LIGHT_OFF_MINUTE = 0

    LATITUDE = 42
    LONGITUDE = -71
    SUNSET_OFFSET_MINUTES = 50
